language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install cimg-dev libmagickcore-dev"
  - export JOBS=max
script: "npm run test"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8